name: dyte
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

executables:
  dyte:

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  cli_util: ^0.4.1
  io: ^1.0.4
  json_annotation: ^4.9.0
  package_config: ^2.1.0
  path: ^1.9.0

dev_dependencies:
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
