name: dyte
description: |
  Dyte: Frontend Tooling at your fingertips
version: 0.0.1-pre
repository: https://github.com/nikeokoronkwo/dyte-dart

environment:
  sdk: ^3.3.0

executables:
  dyte:

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  async: ^2.11.0
  cli_util: ^0.4.1
  frontend_server_client: ^4.0.0
  glob: ^2.1.2
  io: ^1.0.4
  json_annotation: ^4.9.0
  mime: ^1.0.5
  package_config: ^2.1.0
  path: ^1.9.0
  shelf: ^1.4.1
  shelf_packages_handler: ^3.0.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  watcher: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
