name: create_dyte
description: Create a Dyte Application with no hassle and with your favourite tools
version: 0.0.1-rc
repository: https://github.com/nikeokoronkwo/dyte-dart

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  cli_dialog: ^0.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
